### ISSUE TITLE
help me. How i run this?

### ISSUE THREAD

**Issue by codescandy** [cferdinandi/academy-expert-cart-count#1]
How i run this? it show just like below image. 
<img width="851" alt="Screenshot 2022-10-08 at 9 02 17 AM" src="https://user-images.githubusercontent.com/68774600/194686123-aa9ddf33-8304-4a95-b4bf-061f85ba46a7.png">

**Comment by cferdinandi** [comment]
This is for a workshop I'm building. Sorry.
